DROP FUNCTION IF EXISTS CreateStore(INTEGER, INTEGER, VARCHAR(255), VARCHAR(255));

DROP TRIGGER IF EXISTS tUpdateRecruitmentDate ON angeworben;
DROP FUNCTION IF EXISTS fUpdateRecruitmentDate();

DROP TRIGGER IF EXISTS tUpdateProduct ON Ware;
DROP FUNCTION IF EXISTS fUpdateProduct();

DROP TRIGGER IF EXISTS tAddRecruitment ON angeworben;
DROP FUNCTION IF EXISTS fAddRecruitment();

DROP VIEW IF EXISTS AnnualSalesVolume;
DROP VIEW IF EXISTS AllRecruits;
DROP VIEW IF EXISTS AllRecruitionSteps;

ALTER TABLE IF EXISTS Mitarbeiterin DROP CONSTRAINT fk_WorkPlace;
ALTER TABLE IF EXISTS Filiale DROP CONSTRAINT fk_MainCashRegister;

DROP TABLE IF EXISTS schult;
DROP TABLE IF EXISTS angeworben;
DROP TABLE IF EXISTS hergestellt;
DROP TABLE IF EXISTS erstellt;
DROP TABLE IF EXISTS enthaelt;
DROP TABLE IF EXISTS Ware;
DROP TABLE IF EXISTS Produktion;
DROP TABLE IF EXISTS Versandlager;
DROP TABLE IF EXISTS WalkIn;
DROP TABLE IF EXISTS Rechnung;
DROP TABLE IF EXISTS Kassa;
DROP TABLE IF EXISTS Filiale;
DROP TABLE IF EXISTS Mitarbeiterin;
DROP TYPE IF EXISTS ModellEnum;


DROP SEQUENCE IF EXISTS seq_storeID;
DROP SEQUENCE IF EXISTS seq_registerNr;